plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.fml)
    id("maven-publish")
}

val mod_name: String by project
val mod_version: String by project
val mod_id: String by project

version = mod_version

base {
    archivesName = mod_id
}

repositories {
    maven("https://jitpack.io")
    maven("https://maven.limingzxc.top/repository/maven-public/")
}

val loader = configurations.create("loader") {
    configurations.implementation.get().extendsFrom(this)
}

dependencies {
    // Don't modify '1.6.4-MITE' here.
    minecraft("Minecraft:IsTooEasy:1.6.4-MITE")

    // Add fish mod loader dependency
    add("loader", "com.github.MinecraftIsTooEasy:FishModLoader:3.4.2")

    implementation(libs.kotlinLanguage)
}

loom {
    accessWidenerPath = file("src/main/resources/example.accesswidener")
    mergedMinecraftJar()

    fml = loader.files.first()

    // Add the mappings generated by FML to the mappings configuration
    project.dependencies.add("mappings", fmlMCPMappings())

    mods {
        create(mod_name) {
            sourceSet(sourceSets.main.get())
        }
    }
}

tasks.processResources {
    inputs.property("version", mod_version)

    filesMatching("fml.mod.json") {
        expand("version" to mod_version)
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}
